/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 camera.glb
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canon-at-1-retro-camera-9de66868d0f240e985da00c9480bfc82
Title: Canon AT-1 Retro Camera
*/
// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Camera(props) {
//   const { nodes, materials } = useGLTF('/models/camera.glb')

//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh
//           geometry={nodes['#CAM0001_Body_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//         />
//         <mesh
//           geometry={nodes['#CAM0001_Battery_Check_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//           position={[0.05, 0.001, 0.072]}
//         />
//         <mesh
//           geometry={nodes['#CAM0001_Spool_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//           position={[0.05, 0.001, 0.075]}
//         />
//         <mesh
//           geometry={nodes['#CAM0001_Film_Advance_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//           position={[-0.057, 0.001, 0.077]}
//         />
//         <mesh
//           geometry={nodes['#CAM0001_Shutter_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//           position={[-0.035, -0.006, 0.076]}
//         />
//         <mesh
//           geometry={nodes['#CAM0001_Shutter_Speed_#CAM0001_Textures_0'].geometry}
//           material={materials.CAM0001_Textures}
//           position={[-0.057, 0.001, 0.073]}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/camera.glb')

// GPT VERSION
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Edited by Vitaly + ChatGPT mentor edition 😎
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Camera(props) {
  const { nodes, materials } = useGLTF('/models/camera.glb')

  // Исправляем материалы и видимость
  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.side = THREE.DoubleSide
      mat.needsUpdate = true
      mat.envMapIntensity = 1.2
      mat.roughness = 0.6
      mat.metalness = 0.4
    })
  }, [materials])

  return (
    <group {...props} dispose={null}>
      {/* Убираем поворот, ставим нормальную ориентацию */}
      <group rotation={[0, 0, 0]}>
        <mesh
          geometry={nodes['#CAM0001_Body_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
        />
        <mesh
          geometry={nodes['#CAM0001_Battery_Check_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
          position={[0.05, 0.001, 0.072]}
        />
        <mesh
          geometry={nodes['#CAM0001_Spool_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
          position={[0.05, 0.001, 0.075]}
        />
        <mesh
          geometry={nodes['#CAM0001_Film_Advance_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
          position={[-0.057, 0.001, 0.077]}
        />
        <mesh
          geometry={nodes['#CAM0001_Shutter_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
          position={[-0.035, -0.006, 0.076]}
        />
        <mesh
          geometry={nodes['#CAM0001_Shutter_Speed_#CAM0001_Textures_0'].geometry}
          material={materials.CAM0001_Textures}
          position={[-0.057, 0.001, 0.073]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/camera.glb')
